import ProductCard from "@/components/product-card/ProductCard";
import styles from "./page.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <p className={styles.title}>{"مردانه"}</p> */}
      <div className={styles.productContainer}>
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
          />
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
          />
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
        />
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
          />
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
          />
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
        />
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
          />
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
          />
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
        />
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
          />
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
          />
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
        />
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
          />
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
          />
        <ProductCard 
          title="sample"
          subTitle="sfadsfdsfds"
          image=""
          prices={["800000","650000","700000"]}
          colors={["red","blue"]}
        />
      </div>
    </div>
  );
}
